version: '3'

services:
  db-telegram-bot:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_HOST_PORT}:${PG_CONTAINER_PORT}"
  adminer:
    image: adminer
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"
networks:
    default:
        external:
            name: telegram-bot