version: '3'

services:
  db-telegram-bot:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
  adminer:
    image: adminer
    ports:
      - "89:8080"
networks:
    default:
        external:
            name: telegram-bot